<div style="padding:30px; color: white; background-color: #0071CD">
<center>
<img src="img/logoub.jpeg"></img>
<center>
<h1>Algorísmica Avançada</h1>
<h2>Laboratori 4 - Enumeratius</h2>
</center>
</div>

In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

si estem al final (0 caselles buides) -- retorna

recursio for opcions si la opcio es valid-- recurssio
tenim dos sortides que coloquem la fitxa o no la podem colocar i retornem buit

-- hem de veure si satisfa les condicions, el moviment es valid?

-- recomenacio --> comencar per la restriccio mes alta o si es igual a la longitud

-- treure casos base i despres mirar on comencar

<div class="alert alert-info">
<h2>Avís general per a les Pràctiques de Laboratori</h2>

És molt important <b>comentar tot el vostre codi</b>. Comentar el codi no només facilita a altres persones que el llegeixin la compressió del que esteu fent, sinó també a vosaltres mateixos durant el procés de disseny i implementació. D'aquesta forma podreu entendre el vostre propi codi encara que faci molt temps que no el consulteu. A més, a l'hora de ser corregits, un codi comentat s'entén molt millor, la qual cosa ajuda a traslladar al professor les idees que teníeu a l'intentar implementar-lo i encara més en el cas que no ho hagueu pogut acabar-ho amb èxit. No cal comentar cada línia, però si el que fa cada part.

En segon lloc, és molt important <b>respectar les capçaleres de les funcions i estructura de la funció ```return```</b> que s'indiquin a l'enunciat. Tot i que llegim i corregim els vostres codis en detall, fem servir correctors automàtics per guiar i agilitzar el procés i saber quines solucións funcionen i quines no ja d'entrada. 

Axí doncs, si es demana que la funció tingui la següent estructura: 

```python
def exercici1(param1, param2):
    # implementació de la solució
    return resultat 
```

És important que en el notebook existeixi aquesta funció i que no canvieu el nom dels paràmetres ni el tipus de dada retornada.
    
</div>




<div class="alert alert-success">
    <h1>Problema: Edificis</h1>
    <p>
        Volem solucionar el puzzle dels edificis. Donada una graella com la que tenim a continuació (esquerra), volem trobar la solució al puzzle (dreta):
        <center><img src="img/sky-intro.png" width='25%'></center>
        Podem pensar que cada una de les caselles és un solar on hi podem posar un edifici de X plantes. En aquest cas un edifici de 1,2,3 o 4 plantes ja que el tauler és de 4x4.<br>
        Els números que trobem a fora de la graella ens indiquen quants edificis són visibles des d'aquesta posició. Un edifici d'alçada 4 tapa qualsevol edifici que hi ha al darrere com podeu veure en la imatge següent:
        <center><img src="img/sky-rule-3-1.png" width='25%'></center>
        A més, en cada fila i columna de la graella només pot haver-hi un sol edifici de cada alçada, és a dir, no es poden repetir.
        <center><img src="img/skyscrapers.png" width='25%'></center>
        L'objectiu és doncs, donada una graella com la inicial, trobar la configuració d'edificis que satisfà les condicions. Implementeu un algorisme usant backtracking que <b>trobi una solució utilitzant el mínim nombre de crides recursives i minimitzant el temps total d'execució</b>. Per fer-ho haureu de tenir en comptes diferents factors com ara:
        <ol>
            <li> Quin número començareu provant?
            <li> Quina casella serà la primera que omplireu?
        </ol>
    </p>
    
</div>

La funció **format_sky** us ajudarà a visualitzar el tauler del problema.

In [2]:
import numpy as np
from IPython.display import clear_output
import time

def format_sky(board, top, bottom, left, right):
    """
    Funció auxiliar per mostrar la matriu del Problema 1 en forma de graella.
    """
    _str = ""
    
    # Files
    for v in top:
        _str+="   "+ str(v)
    _str = "  " + _str + "\n"

    for idx, i in enumerate(board):
        _str+= "   +"+ ("-"*((board.shape[1]*4)-1)) +"+\n"
        _str+= f" {left[idx]} | "
        
        # Columnes
        for j in i:   
            if j!=0:
                _str+= str(j)+" | "
            else:
                _str+= "  | "
            
        _str+= f"{right[idx]} \n"
    _str+= "   +"+ ("-"*((board.shape[1]*4)-1))+"+\n"
    
    _bot = ""
    for v in bottom:
        _bot+="   "+str(v)
    _str += "  " + _bot
    
    return _str.replace('0',' ')

Veieu un exemple de com utilitzar aquesta funció:


In [3]:
# Amb aquesta funció es mostren totes les caselles del tauler
# Les caselles que contenen un zero es mostren buides

# Creem unes restriccions i un tauler 
top, bottom, left, right = [0,0,0], [3,0,0], [0,0,0], [0,0,1]
grid = np.zeros((len(left), len(top)), dtype='int')

print('Tauler:')
print(format_sky(grid, top, bottom, left, right))

Tauler:
              
   +-----------+
   |   |   |   |   
   +-----------+
   |   |   |   |   
   +-----------+
   |   |   |   | 1 
   +-----------+
     3        


La funció **delayed_print** us permet bloquejar temporalment un 'print' per si voleu veure les accions que fa a cada pas el vostre algorisme.<br>
No heu d'utilitzar-la a l'entrega ja que el programa tardarà molt més del necessari, utilitzeu-la només mentre programeu la solució.

In [4]:
def delayed_print(grid, top, bottom, left, right, sleep_time=0.02):
    """
    Funció auxiliar que bloqueja temporalment la funció 'print' per veure l'evolució de l'algorisme.
    """
    print(format_sky(grid, top, bottom, left, right))
    clear_output(wait=True)
    time.sleep(sleep_time)

In [19]:
top, bottom, left, right = [0,0,0], [3,0,0], [0,0,0], [0,0,1]
grid = np.zeros((len(left), len(top)), dtype='int')

for i in range(0, len(left)):
    for j in range(0, len(top)):
        grid[i][j] = np.random.randint(1,4)
        delayed_print(grid, top, bottom, left, right, sleep_time=0.25)

              
   +-----------+
   | 3 | 2 | 1 |   
   +-----------+
   | 1 | 2 | 2 |   
   +-----------+
   | 3 | 3 | 2 | 1 
   +-----------+
     3        


In [ ]:
###
# LES VOSTRES FUNCIONS EXTRES AQUÍ
###

# Amb els valors que hi ha fins ara (incloent zeros), és possible arribar a complir la restricció?
# No és una validació final: és un filtre que et diu si podria arribar a ser possible o no
def satisfies_petit(fila, restriccio, dreta_baix):
    n = len(fila)
    
    # si la restriccio es 0 retornem true, pqe qualsevol combinacio serà real
    if restriccio == 0:
        return True

    # comptaré els edificis visbles que tinc
    # no fem servir la funcio auxiliar comptadora d'edificis perquè aquella nomes compta si NO hi han zeros
    max_altura = 0
    edificis_visibles = 0
    ceros = 0
    
    for altura in fila:
        if altura == 0:
            ceros += 1
        else:
            if altura > max_altura:
                edificis_visibles += 1
                max_altura = altura

    # condicio 1: si veig mes edificis dels que puc veure
    if edificis_visibles > restriccio and dreta_baix == False:
        return False
    
    # condicio 2: si no hi ha zeros ha de coincidir exactement
    if ceros == 0 and edificis_visibles != restriccio:
        return False
    
    # condicio 3: si tots els zeros fossin edificis mes alts no podriem arribar a la restriccios
    # cas [0, 4, 3, 1]
    # Encara que tots els zeros fossin edificis més alts i visibles, no podríem arribar a la restricció
    if edificis_visibles + ceros < restriccio:
        return False
    
    # si no es cumpleix cap de les condicions, retornem un true final
    return True


def satisfies(grid, x, y, num, top, bottom, left, right):
    """
    Donat un tauler, un punt amb coordenades (x,y) i un nombre 'num', comprova si és possible assignar-lo a la posició (x,y) 
    donades les restriccions del problema.
    
    Params
    ------
    :grid: Una matriu de numpy
    :x,y: Un punt de la matriu on volem posar el nombre 'num'
    :num: Un nombre enter
    :top, bottom, left, right: Els nombres de fora del tauler de la part superior, inferior, esquerra i dreta, respectivament.
    
    Returns
    -------
    :b: Un boleà True/False depenent de si el nombre 'num' pot ser col·locat a la casella (x,y) o no.
    """
    
    # grid es la matriu de numpy, shape és una tupla amb les seves dimensions, per tant agafem el primer element de la tupla 
    # com que es tracta d'una matriu quadrada, num files = num columnes
    num_files = grid.shape[0]

    # Primer mirem si hi ha algun numero a la fila o columna que a estigui posat i sigui igual al num
    for i in range(num_files):
        # observem la seva columna
        if grid[i][y] == num:
            return False
    for j in range(num_files):
        # ara observem la seva fila
        if grid[x][j] == num:
            return False
        
    # Assignem el nombre a la casella temporalment, si no es possible que estigui en aquesta posicio, ja el traurem
    grid [x][y] = num
    
    
    # Ara comprovem si stisfa les restriccions de top o de bottom (es a dir, ens fixem amb la columna)
    columna = grid[:, y]
    
    if not satisfies_petit(columna, top[y], False):
        # Cas que NO tinguem la columna completa:
        grid[x][y] = 0
        return False
    if not satisfies_petit(columna[::-1], bottom[y], True):
        # Cas que NO tinguem la columna completa:
        grid[x][y] = 0
        return False
    
    
    # Ara comprovem si stisfa les restriccions de left o de right (es a dir, ens fixem amb la fila)
    fila = grid[x, :]
    
    if not satisfies_petit(fila, left[x], True):
        grid[x][y] = 0
        return False
    if not satisfies_petit(fila[::-1], right[x], False):
        grid[x][y] = 0
        return False
        
    #important tornar la posicio en el seu estat original (que es 0)
    grid[x][y] = 0
    
    #si ha arribat fins aqui, és que si que cumpleix totes les restriccions
    return True
    

def skyscrapper_backtracking(grid, top, bottom, left, right):  
    """
    Funció que implementa l'algorisme de backtracking
    
    Params
    ------
    :grid: Una matriu de tipus numpy
    :top, bottom, left, right: Els nombres de fora del tauler de la part superior, inferior, esquerra i dreta, respectivament.
    
    Returns
    -------
    :grid: La matriu plena amb la solució correcta o bé False en cas que no tingui solució.    
    """
    
    # NO esborreu aquestes dues línies, serveien per saber quants cops es crida aquesta funció
    # ----------------------------------------------------------------------------------------
    global num_recursive_calls 
    num_recursive_calls += 1
    # ----------------------------------------------------------------------------------------
    
    # EL TEU CODI AQUÍ

    # si la matriu esta plena ha de retornar la matriu --> 
    # np.all(grid != 0) --> retorna si tots els espais de la matriu son diferent de 0 --> esta plena
    # si esta plena, és pqe l'hem pogut omplir, i si l'hem pogut omplir, és que té solució
    if np.all(grid != 0):
        return grid
    
    #prenem la llargada de les files/columnes
    n = grid.shape[0]
    
    # estem omplint de dalt a baix i d'esquerra a dreta (per aixo al satisfies_petit hi posem esquerra_baix)
    for i in range(n):
        for j in range (n):
            # les caselles que ja estan omplertes ens les saltem, volem omplir les dels 0's
            if grid[i][j] == 0:
                # Probarem totes les alçades possibles
                for altura in range(1, n + 1):
                    if satisfies (grid, i, j, altura, top, bottom, left, right):
                        grid[i][j] = altura
                        
                        # Crida recursiva
                        result = skyscrapper_backtracking(grid, top, bottom, left, right)
                        if result is not False:
                            return result
                        
                        # part del backtarck: trec la solucio que no mha anat bé (torno enrere) i en probaré una altra
                        grid[i][j] = 0
                        
                # si arriba aqui, es pq cap altura funciona, per tant retornem false        
                return False
            
    # si arribes aqui, és pq no hi ha cap 0, la matriu està completa i és correcta
    return grid

def skyscrapper_fale(top, bottom, left, right):
    """
    Funció principal del problema. Rep quatre llistes corresponents als nombres que hi ha fora del tauler.
    
    Params
    ------
    :top, bottom, left, right: Els nombres de fora del tauler de la part superior, inferior, esquerra i dreta, respectivament.
    """
    
    # Inicialitzem una matriu de zeros
    grid = np.zeros((len(left), len(top)), dtype='int')
    
    # Cridem a la funció que soluciona el problema mitjançant backtracking
    sol = skyscrapper_backtracking(grid, top, bottom, left, right)   
    
    # Mostrem el resultat en el cas que trobem una solució o mostrem un error en cas contrari.
    if sol is not False:
        print(format_sky(np.array(sol), top, bottom, left, right))
    else:
        print('No solution found')


aquest es el nou


In [65]:
# Amb els valors que hi ha fins ara (incloent zeros), és possible arribar a complir la restricció?
# No és una validació final: és un filtre que et diu si podria arribar a ser possible o no
def satisfies_petit(fila, restriccio, dreta_baix):
    n = len(fila)
    
    # si la restriccio es 0 retornem true, pqe qualsevol combinacio serà real
    if restriccio == 0:
        return True

    # comptaré els edificis visbles que tinc
    # no fem servir la funcio auxiliar comptadora d'edificis perquè aquella nomes compta si NO hi han zeros
    max_altura = 0
    edificis_visibles = 0
    ceros = 0
    
    for altura in fila:
        if altura == 0:
            ceros += 1
        else:
            if altura > max_altura:
                edificis_visibles += 1
                max_altura = altura

    # condicio 1: si veig mes edificis dels que puc veure
    if edificis_visibles > restriccio and dreta_baix == False:
        return False
    
    # condicio 2: si no hi ha zeros ha de coincidir exactement
    if ceros == 0 and edificis_visibles != restriccio:
        return False
    
    # condicio 3: si tots els zeros fossin edificis mes alts no podriem arribar a la restriccios
    # cas [0, 4, 3, 1]
    # Encara que tots els zeros fossin edificis més alts i visibles, no podríem arribar a la restricció
    if edificis_visibles + ceros < restriccio:
        return False
    
    # si no es cumpleix cap de les condicions, retornem un true final
    return True


def satisfies(grid, x, y, num, top, bottom, left, right):
    """
    Donat un tauler, un punt amb coordenades (x,y) i un nombre 'num', comprova si és possible assignar-lo a la posició (x,y) 
    donades les restriccions del problema.
    
    Params
    ------
    :grid: Una matriu de numpy
    :x,y: Un punt de la matriu on volem posar el nombre 'num'
    :num: Un nombre enter
    :top, bottom, left, right: Els nombres de fora del tauler de la part superior, inferior, esquerra i dreta, respectivament.
    
    Returns
    -------
    :b: Un boleà True/False depenent de si el nombre 'num' pot ser col·locat a la casella (x,y) o no.
    """
    
    # grid es la matriu de numpy, shape és una tupla amb les seves dimensions, per tant agafem el primer element de la tupla 
    # com que es tracta d'una matriu quadrada, num files = num columnes
    num_files = grid.shape[0]

    # Primer mirem si hi ha algun numero a la fila o columna que a estigui posat i sigui igual al num
    for i in range(num_files):
        # observem la seva columna
        if grid[i][y] == num:
            return False
    for j in range(num_files):
        # ara observem la seva fila
        if grid[x][j] == num:
            return False
        
    # Assignem el nombre a la casella temporalment, si no es possible que estigui en aquesta posicio, ja el traurem
    grid [x][y] = num
    
    
    # Ara comprovem si stisfa les restriccions de top o de bottom (es a dir, ens fixem amb la columna)
    columna = grid[:, y]
    
    if not satisfies_petit(columna, top[y], False):
        # Cas que NO tinguem la columna completa:
        grid[x][y] = 0
        return False
    if not satisfies_petit(columna[::-1], bottom[y], True):
        # Cas que NO tinguem la columna completa:
        grid[x][y] = 0
        return False
    
    
    # Ara comprovem si stisfa les restriccions de left o de right (es a dir, ens fixem amb la fila)
    fila = grid[x, :]
    
    if not satisfies_petit(fila, left[x], True):
        grid[x][y] = 0
        return False
    if not satisfies_petit(fila[::-1], right[x], False):
        grid[x][y] = 0
        return False
        
    # important tornar la posicio en el seu estat original (que es 0)
    grid[x][y] = 0
    
    #si ha arribat fins aqui, és que si que cumpleix totes les restriccions
    return True

def skyscrapper_backtracking(grid, top, bottom, left, right):  
    """
    Funció que implementa l'algorisme de backtracking
    
    Params
    ------
    :grid: Una matriu de tipus numpy
    :top, bottom, left, right: Els nombres de fora del tauler de la part superior, inferior, esquerra i dreta, respectivament.
    
    Returns
    -------
    :grid: La matriu plena amb la solució correcta o bé False en cas que no tingui solució.    
    """
    
    # NO esborreu aquestes dues línies, serveien per saber quants cops es crida aquesta funció
    # ----------------------------------------------------------------------------------------
    global num_recursive_calls 
    num_recursive_calls += 1
    # ----------------------------------------------------------------------------------------
    
    # EL TEU CODI AQUÍ

    # si la matriu esta plena ha de retornar la matriu --> 
    # np.all(grid != 0) --> retorna si tots els espais de la matriu son diferent de 0 --> esta plena
    # si esta plena, és pqe l'hem pogut omplir, i si l'hem pogut omplir, és que té solució
    if np.all(grid != 0):
        return grid
    
    #prenem la llargada de les files/columnes
    n = grid.shape[0]

    columnes_omplertes = []
   
    # tractem casos especials!!
    for i, valor in enumerate(left):
        if valor == 1:
            grid[i][0] = n
            columnes_omplertes.append((i,0))
        if valor == n:
            for j in range(n):
                grid[i][j] = j+1
                columnes_omplertes.append((i,j))
    
    for i, valor in enumerate(right):
        if valor == 1:
            grid[i][n-1] = n
            columnes_omplertes.append((i,n-1))
        if valor == n:
            for j in range(n):
                grid[i][j] = n-j
                columnes_omplertes.append((i,j))
    
    for j, valor in enumerate(top):
        if valor == 1:
            grid[0][j] = n
            columnes_omplertes.append((0,j))
        if valor == n:
            for i in range(n):
                grid[i][j] = i+1
                columnes_omplertes.append((i,j))

    for j, valor in enumerate(bottom):
        if valor == 1:
            grid[n-1][j] = n
            columnes_omplertes.append((n-1,j))
        if valor == n:
            for i in range(n):
                grid[i][j] = n-i
                columnes_omplertes.append((i,j))

    # estem omplint de dalt a baix i d'esquerra a dreta (per aixo al satisfies_petit hi posem esquerra_baix)
    for i in range(n):
        for j in range (n):
            if (i, j) in columnes_omplertes:
                continue
            # les caselles que ja estan omplertes ens les saltem, volem omplir les dels 0's
            if grid[i][j] == 0:
                # Probarem totes les alçades possibles
                for altura in range(1, n + 1):
                    print (altura)
                    if satisfies (grid, i, j, altura, top, bottom, left, right):
                        grid[i][j] = altura
                        print (grid)
                        # Crida recursiva
                        result = skyscrapper_backtracking(grid, top, bottom, left, right)
                        if result is not False:
                            return result
                        
                        # part del backtarck: trec la solucio que no mha anat bé (torno enrere) i en probaré una altra
                        grid[i][j] = 0
                        print (grid)
                        
                # si arriba aqui, es pq cap altura funciona, per tant retornem false        
                return False
            
    # si arribes aqui, és pq no hi ha cap 0, la matriu està completa i és correcta
    return grid

def skyscrapper(top, bottom, left, right):
    """
    Funció principal del problema. Rep quatre llistes corresponents als nombres que hi ha fora del tauler.
    
    Params
    ------
    :top, bottom, left, right: Els nombres de fora del tauler de la part superior, inferior, esquerra i dreta, respectivament.
    """
    
    # Inicialitzem una matriu de zeros
    grid = np.zeros((len(left), len(top)), dtype='int')
    
    # Cridem a la funció que soluciona el problema mitjançant backtracking
    sol = skyscrapper_backtracking(grid, top, bottom, left, right)   
    
    # Mostrem el resultat en el cas que trobem una solució o mostrem un error en cas contrari.
    if sol is not False:
        print(format_sky(np.array(sol), top, bottom, left, right))
    else:
        print('No solution found')


In [66]:
num_recursive_calls = 0
t0 = time.perf_counter()
skyscrapper([0,0,0],
            [3,0,0],
            [0,0,0],
            [0,0,1])
t1 = time.perf_counter()
print('Crides recursives:', num_recursive_calls)
print(f'Temps: {t1-t0:.2f}s')

1
[[3 1 0]
 [2 0 0]
 [1 0 3]]
1
2
[[3 1 2]
 [2 0 0]
 [1 0 3]]
1
2
3
[[3 1 2]
 [2 3 0]
 [1 0 3]]
1
[[3 1 2]
 [2 3 1]
 [1 0 3]]
1
2
[[3 1 2]
 [2 3 1]
 [1 2 3]]
              
   +-----------+
   | 3 | 1 | 2 |   
   +-----------+
   | 2 | 3 | 1 |   
   +-----------+
   | 1 | 2 | 3 | 1 
   +-----------+
     3        
Crides recursives: 6
Temps: 0.00s


In [67]:
num_recursive_calls = 0
t0 = time.perf_counter()
skyscrapper([4,2,1,2,3],
            [1,4,3,2,2],
            [3,2,3,2,1],
            [3,4,1,2,2])
t1 = time.perf_counter()
print('Crides recursives:', num_recursive_calls)
print(f'Temps: {t1-t0:.2f}s')

1
[[1 0 5 0 0]
 [0 0 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
1
2
[[1 2 5 0 0]
 [0 0 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
1
2
3
[[1 2 5 3 0]
 [0 0 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
1
2
3
4
5
[[1 2 5 0 0]
 [0 0 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
4
[[1 2 5 4 0]
 [0 0 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
1
2
3
[[1 2 5 4 3]
 [0 0 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
1
2
[[1 2 5 4 3]
 [2 0 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
1
[[1 2 5 4 3]
 [2 1 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
1
2
3
4
5
[[1 2 5 4 3]
 [2 0 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
2
3
[[1 2 5 4 3]
 [2 3 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
1
[[1 2 5 4 3]
 [2 3 1 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
1
2
3
4
5
[[1 2 5 4 3]
 [2 3 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
2
3
4
5
[[1 2 5 4 3]
 [2 0 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
4
[[1 2 5 4 3]
 [2 4 0 0 0]
 [0 0 0 0 5]
 [0 0 0 0 0]
 [5 0 0 0 0]]
1
[[

In [54]:
num_recursive_calls = 0
t0 = time.perf_counter()
skyscrapper([0,0,3,0],
            [0,2,2,0],
            [0,0,0,0],
            [0,2,0,0])
t1 = time.perf_counter()
print('Crides recursives:', num_recursive_calls)
print(f'Temps: {t1-t0:.2f}s')

[[1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 2 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 2 3 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [0 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 0 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 1 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 1 2]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 1 2]
 [4 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 1 2]
 [4 3 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 1 2]
 [4 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 1 2]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 1 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 0 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 2 0]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 2 1]
 [0 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 2 1]
 [4 0 0 0]]
[[1 2 3 4]
 [2 1 4 3]
 [3 4 2 1]
 [4 3 0 0]]
[[1 2 3 4]

VALE NO LHI FACIS CAS A AIXO DIRIA QUE JA HO HE SOLUCIONAT 🤩🤩🤩🤩🤩🤩


BORRAR: Aquest exemple de sota l'he posat jo (me lha fet el xat). Basicament pqe, com pots veure, tots els exemples d'aqui sobre em donen que no tenen solucio, pero tmpoc trobo l'error en el codi... El xat mha dit que el codi esta bé, i que aquests exemples ja és normal que no tinguin solucio i mha dit: "mira, et dono aquest exemple que SÍ que te solucio". I és veritat que quan el faig si que em dona una solucio... Pro clar, ho trobo raro que tots els exemples que ens hagin donat no tinguin solucio saps?

In [11]:

num_recursive_calls = 0

top    = [2, 1, 3]
bottom = [0, 0, 0]
left   = [0, 0, 0]
right  = [0, 0, 0]

t0 = time.perf_counter()
skyscrapper(top, bottom, left, right)
t1 = time.perf_counter()

print('Crides recursives:', num_recursive_calls)
print(f'Temps: {t1-t0:.2f}s')

     2   1   3
   +-----------+
   | 2 | 3 | 1 |   
   +-----------+
   | 3 | 1 | 2 |   
   +-----------+
   | 1 | 2 | 3 |   
   +-----------+
              
Crides recursives: 38
Temps: 0.00s


<div class="alert alert-info">
<center>
  <h1>Entrega</h1>
</center>

<p>
L'entrega es farà a través del campus virtual. Teniu fins el dia <b>15 de Desembre a les 23:59</b> per entregar la pràctica. A la tasca que obrirem al campus, <b>només heu d'entregar aquest fitxer .ipynb</b>. El notebook ha de tenir com a nom:
</p>
<p>
    <code>Grup_Cognom1_Nom1_Grup_Cognom2_Nom2_Enumeratius.ipynb</code>
</p>
On 'Grup' és una sola lletra que identifica el <b>grup de laboratori</b> on esteu matriculats (A, B, C, D, E, F). <b>Només ha d'entregar un dels dos membres de la parella.</b>

És imprescindible que respecteu el format de les funcions i que el vostre codi estigui degudament comentat.<br><br>
</div>